import { IAccountService } from "./Iaccount.service";
import { IUserService } from "./Iuser.service";
import { ICategoryService } from "./Icategory.service";
import { IProductService } from "./Iproduct.service";
import { IProductVariantService } from "./Iproduct-variant.service";
import { IAttributeService } from "./Iattribute.service";
import { IStaffAttendanceService } from "./Istaff-attendance.service";
import { IOrderService } from "./Iorder.service";
import { IOrderItemService } from "./Iorder-item.service";
import { IPaymentService } from "./Ipayment.service";
import { IStaffSalaryService } from "./Istaff-salary.service";
import { IDashboardService } from "./Idashboard.service";
import { IBrandNameService } from "./Ibrand-name.service";
import { IStaffService } from "./Istaff.service";
import { IStoreService } from "./Istore.service";
import { IPurchaseService } from "./ipurchase.service";
import { ISupplierService } from "./Isupplier.service";
import { ICartService } from "./Icart.service";
import { ICheckoutService } from "./Icheckout.service";
import { IUserSessionService } from "./Iuser-session.service";
import { IReviewService } from "./Ireview.service";
import { IReviewReplyService } from "./Ireview-reply.service";
import { IWishlistService } from "./Iwishlist.service";
import { IMasterAttributeService } from "./Imaster-attribute.service";
import { IMasterEntryService } from "./Imaster-entry.service";
import { IPriceHistoryService } from "./Iprice-history.service";

export default interface IUnitOfService {
  User: IUserService;
  Account: IAccountService;
  Category: ICategoryService;
  Product: IProductService;
  ProductVariant: IProductVariantService;
  Attribute: IAttributeService;
  StaffAttendance: IStaffAttendanceService;
  Order: IOrderService;
  OrderItem: IOrderItemService;
  Payment: IPaymentService;
  StaffSalary: IStaffSalaryService;
  Dashboard: IDashboardService;
  BrandName: IBrandNameService;
  Staff: IStaffService;
  Store: IStoreService;
  Purchase: IPurchaseService;
  Supplier: ISupplierService;
  Cart: ICartService;
  Checkout: ICheckoutService;
  UserSession: IUserSessionService;
  Review: IReviewService;
  ReviewReply: IReviewReplyService;
  Wishlist: IWishlistService;
  MasterAttribute: IMasterAttributeService;
  MasterEntry: IMasterEntryService;
  PriceHistory: IPriceHistoryService;
}
